### ISSUE TITLE
Adding custom attributes is only possible by changing the Core Data Schema

### ISSUE THREAD

**Issue by LaurensJN** [LaurensJN/IFC#1]
I added a Domain Specific Schema _IfcHeritageDomain_ to deal with any new Types in the Heritage MVD. Such Type is the IfcSignificanceEnum. This type will be added to elements, to communicate the significance value to 

To add the significance to all IfcElement, I need to add it to the IfcElement in the core data schema. This is probably not how it should work, but I couldn't figure a way around that. 
<img src="https://user-images.githubusercontent.com/23737460/108686687-10595980-74f6-11eb-89b9-4909a6c5733d.png " width="200">

Maybe there is a way to add the attribute to IfcElement, not in the schema where IfcElement is defined itself, but somewhere where it is only applicable to the Heritage MVD

**Comment by pjanck** [comment]
Don't add attributes to stuff already existing. That would be a change to the IFC schema, which is not possible in our study.

You should define a special PropertySet, with certain properties required.
