### ISSUE TITLE
Map Cultural Heritage Object to Ifc class

### ISSUE THREAD

**Issue by LaurensJN** [LaurensJN/IFC#3]
The cultural heritage, conservation plan exchange model we created is hierarchical. The top element is the conservation plan, which in ifc would be equivalent to the IfcProject class. 

The IfcProject has one or more cultural heritage objects (see picture). These heritage objects could be a building, but also a site or a garden. This object **must** have a HeritageType property,  a construction period etc. An IfcProject could have multiple heritage objects. I first thought I could map that to IfcSpatialStructureElement, but for example IfcSpace is also part of this class. IfcSpace does not necessarily need to have a HeritageType etc. Is it better to just use an IfcSite as equivalent to the cultural heritage object? 

![image](https://user-images.githubusercontent.com/23737460/109167538-26794b00-777e-11eb-9239-ec062452b162.png)

**Comment by pjanck** [comment]
I'd recommend being as specific as possible. So including only those requirements that are needed.

I'd suggest to map cultural heritage object to `IfcBuilding`.

**Comment by LaurensJN** [comment]
I mapped it to IfcSite, for me that is more appropriate (in the sense that one site 'contains' one type of cultural heritage, but a project could have multiple sites) . IfcBuilding would not be appropriate because this would exclude the Cultural Landscape heritage type for example.
