### ISSUE TITLE
Assigning properties for IfcSurface

### ISSUE THREAD

**Issue by LaurensJN** [LaurensJN/IFC#8]
I would like to assign properties to IfcSurfaces (for example for stratigraphic analysis on buildings). 
IfcSurfaces does not inherit HasProperties or IsDefinedBy, so there is not really a clear way to add properties to an IfcSurface.
The idea is that an object (say a wall) could be deconstructed into multiple parts that have different properties, different time periods etc. 

Is there a better way to do this? Would it be enough to add properties to the IfcMaterialDefinition (so for example a wall could have a constituent set with multiple materials, that contain these properties)

**Comment by pjanck** [comment]
Usually, walls (etc.) are subdivided into constituents, which in turn can have individual properties.

What may prove useful, is also `IfcSurfaceFeatureAddition` (or sth like that), if you for example wish to convey a different covering of the wall added at some other time.

**Comment by LaurensJN** [comment]
IfcSurfaceFeature is a modification at (onto, or into) of the surface of an element. Parts of the surface of the entire surface may be affected. The volume and mass of the element may be increased, remain unchanged, or be decreased by the surface feature, depending on manufacturing technology. However, any increase or decrease of volume is small compared to the total volume of the element.

It's part child IfcElement so it inherits these property sets! 

This is what I need, thanks!
